[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../../lib/rust" }
itertools = "0.10.5"
rust-crypto = "0.2.36"

[[bin]]
name = "2021_01"
path = "01/main.rs"

[[bin]]
name = "2021_02"
path = "02/main.rs"

[[bin]]
name = "2021_03"
path = "03/main.rs"
